require('dotenv').config();

const {
  PORT = 8022,
  STREAM_PORT,
  FRONTEND_URL,
  ENV,
  KAFKA_TOPIC_VIDEO,
  KAFKA_USERNAME,
  KAFKA_PASSWORD,
  KAFKA_BOOTSTRAP_SERVERS,
  KAFKA_CLIENT_ID,
} = process.env;

module.exports = {
  PORT,
  STREAM_PORT,
  FRONTEND_URL,
  ENV,
  KAFKA_TOPIC_VIDEO,
  KAFKA_USERNAME,
  KAFKA_PASSWORD,
  KAFKA_BOOTSTRAP_SERVERS,
  KAFKA_CLIENT_ID,
};
